version: '3'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile.app
    container_name: api
    environment:
      TZ: America/Sao_Paulo
      DB1_URL: ${DB1_URL}
      DB2_URL: ${DB2_URL}
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - db1
      - db2

  db1:
    image: postgres:13
    container_name: db1
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: ${DB1_USER}
      POSTGRES_PASSWORD: ${DB1_PASSWORD}
      POSTGRES_DB: ${DB1_DB}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db1_data:/var/lib/postgresql/data

  db2:
    image: postgres:13
    container_name: db2
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: ${DB2_USER}
      POSTGRES_PASSWORD: ${DB2_PASSWORD}
      POSTGRES_DB: ${DB2_DB}
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - db2_data:/var/lib/postgresql/data

  dagster:
    build:
      context: ./dagster
      dockerfile: Dockerfile.dag
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8000:3000"
    networks:
      - app-network
    depends_on:
      - api
      - db1
      - db2

volumes:
  db1_data:
  db2_data:

networks:
  app-network:
    driver: bridge