FROM python:3.11-slim

WORKDIR /dagster

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 3000

CMD ["dagster", "dev", "-f", "pipeline.py", "-h", "0.0.0.0", "-p", "3000"]
